-- MySQL Script generated by MySQL Workbench
-- Thu Oct 30 16:44:21 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema xmate
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema xmate
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `xmate` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `xmate` ;

-- -----------------------------------------------------
-- Table `xmate`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xmate`.`users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `is_active` BIT(1) NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `email` VARCHAR(120) NULL DEFAULT NULL,
  `full_name` VARCHAR(120) NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `sdt` VARCHAR(10) NULL DEFAULT NULL,
  `luong` DECIMAL(18,2) NULL DEFAULT NULL,
  `username` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UKr43af9ap4edm43mmtq01oddj6` (`username` ASC) VISIBLE,
  UNIQUE INDEX `UK6dotkott2kjsp8vw4d0m25fb7` (`email` ASC) VISIBLE,
  UNIQUE INDEX `UKcmb8bhcltpsqxpao6hvpulwbk` (`sdt` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `xmate`.`activity_logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xmate`.`activity_logs` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `action` VARCHAR(50) NULL DEFAULT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `diff_json` JSON NULL DEFAULT NULL,
  `entity_id` BIGINT NULL DEFAULT NULL,
  `entity_type` VARCHAR(50) NULL DEFAULT NULL,
  `actor_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK5wnh8r1e5ffup2wu2shpwywak` (`actor_id` ASC) VISIBLE,
  CONSTRAINT `FK5wnh8r1e5ffup2wu2shpwywak`
    FOREIGN KEY (`actor_id`)
    REFERENCES `xmate`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `xmate`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xmate`.`customers` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(6) NOT NULL,
  `dob` DATE NULL DEFAULT NULL,
  `email` VARCHAR(120) NOT NULL,
  `enabled` BIT(1) NOT NULL,
  `fullname` VARCHAR(120) NULL DEFAULT NULL,
  `gender` VARCHAR(1) NULL DEFAULT NULL,
  `height_cm` INT NULL DEFAULT NULL,
  `oauth_provider` VARCHAR(40) NULL DEFAULT NULL,
  `oauth_subject` VARCHAR(128) NULL DEFAULT NULL,
  `password_hash` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `weight_kg` INT NULL DEFAULT NULL,
  `token_user` VARCHAR(160) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_customers_email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `uk_customers_oauth_pair` (`oauth_provider` ASC, `oauth_subject` ASC) VISIBLE,
  UNIQUE INDEX `UKmpsywtxmpvc5hwwmneu7hj7mh` (`token_user` ASC) VISIBLE,
  INDEX `ix_customers_email` (`email` ASC) VISIBLE,
  INDEX `ix_customers_oauth` (`oauth_provider` ASC, `oauth_subject` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `xmate`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xmate`.`addresses` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `district` VARCHAR(255) NULL DEFAULT NULL,
  `line1` VARCHAR(255) NULL DEFAULT NULL,
  `line2` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  `ward` VARCHAR(255) NULL DEFAULT NULL,
  `customer_id` BIGINT NULL DEFAULT NULL,
  `is_default` BIT(1) NULL DEFAULT NULL,
  `full_name` VARCHAR(120) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKhrpf5e8dwasvdc5cticysrt2k` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `FKhrpf5e8dwasvdc5cticysrt2k`
    FOREIGN KEY (`customer_id`)
    REFERENCES `xmate`.`customers` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `xmate`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xmate`.`categories` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `is_active` BIT(1) NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  `slug` VARCHAR(160) NOT NULL,
  `parent_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UKoul14ho7bctbefv8jywp5v3i2` (`slug` ASC) VISIBLE,
  INDEX `FKsaok720gsu4u2wrgbk10b5n8d` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `FKsaok720gsu4u2wrgbk10b5n8d`
    FOREIGN KEY (`parent_id`)
    REFERENCES `xmate`.`categories` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `xmate`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xmate`.`products` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(6) NOT NULL,
  `description` LONGTEXT NULL DEFAULT NULL,
  `fit` VARCHAR(60) NULL DEFAULT NULL,
  `gender` ENUM('MEN', 'UNISEX', 'WOMEN') NULL DEFAULT NULL,
  `material` VARCHAR(120) NULL DEFAULT NULL,
  `name` VARCHAR(160) NOT NULL,
  `slug` VARCHAR(200) NOT NULL,
  `status` ENUM('ACTIVE', 'DRAFT', 'INACTIVE') NOT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `category_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UKostq1ec3toafnjok09y9l7dox` (`slug` ASC) VISIBLE,
  INDEX `FKog2rp4qthbtt2lfyhfo32lsw9` (`category_id` ASC) VISIBLE,
  CONSTRAINT `FKog2rp4qthbtt2lfyhfo32lsw9`
    FOREIGN KEY (`category_id`)
    REFERENCES `xmate`.`categories` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `xmate`.`product_variants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xmate`.`product_variants` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `is_active` BIT(1) NOT NULL,
  `barcode` VARCHAR(64) NULL DEFAULT NULL,
  `color` VARCHAR(60) NULL DEFAULT NULL,
  `compare_at_price` DECIMAL(12,2) NULL DEFAULT NULL,
  `cost` DECIMAL(12,2) NULL DEFAULT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `price` DECIMAL(12,2) NOT NULL,
  `size` VARCHAR(32) NULL DEFAULT NULL,
  `sku` VARCHAR(64) NOT NULL,
  `stock_policy` ENUM('BACKORDER', 'DENY') NOT NULL,
  `weight_gram` INT NULL DEFAULT NULL,
  `product_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UKq935p2d1pbjm39n0063ghnfgn` (`sku` ASC) VISIBLE,
  INDEX `FKosqitn4s405cynmhb87lkvuau` (`product_id` ASC) VISIBLE,
  CONSTRAINT `FKosqitn4s405cynmhb87lkvuau`
    FOREIGN KEY (`product_id`)
    REFERENCES `xmate`.`products` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 87
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `xmate`.`suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xmate`.`suppliers` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(160) NULL DEFAULT NULL,
  `name` VARCHAR(160) NOT NULL,
  `note` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `xmate`.`purchase_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xmate`.`purchase_orders` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(40) NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `expected_date` DATE NULL DEFAULT NULL,
  `status` ENUM('CANCELLED', 'DRAFT', 'PARTIALLY_RECEIVED', 'RECEIVED', 'SUBMITTED') NOT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `supplier_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK3d8hk9ugqwxqofma6vfn1n62x` (`code` ASC) VISIBLE,
  INDEX `FKrpdasmb8y8xs5tiy4369xpinq` (`supplier_id` ASC) VISIBLE,
  CONSTRAINT `FKrpdasmb8y8xs5tiy4369xpinq`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `xmate`.`suppliers` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `xmate`.`purchase_order_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xmate`.`purchase_order_items` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `cost` DECIMAL(12,2) NOT NULL,
  `qty` INT NOT NULL,
  `received_qty` INT NOT NULL,
  `po_id` BIGINT NOT NULL,
  `variant_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK5y0w29ahv8gqn5hq6ug5f9u9o` (`po_id` ASC) VISIBLE,
  INDEX `FK8vvrbcsu89a1ddsrfygegjio` (`variant_id` ASC) VISIBLE,
  CONSTRAINT `FK5y0w29ahv8gqn5hq6ug5f9u9o`
    FOREIGN KEY (`po_id`)
    REFERENCES `xmate`.`purchase_orders` (`id`),
  CONSTRAINT `FK8vvrbcsu89a1ddsrfygegjio`
    FOREIGN KEY (`variant_id`)
    REFERENCES `xmate`.`product_variants` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `xmate`.`batches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xmate`.`batches` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `qty_received` INT NOT NULL,
  `received_at` DATETIME(6) NOT NULL,
  `unit_cost` DECIMAL(12,2) NOT NULL,
  `po_item_id` BIGINT NULL DEFAULT NULL,
  `variant_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKkmi4j0c2eed1nlkmo5kmoaxj8` (`po_item_id` ASC) VISIBLE,
  INDEX `FK5tuqpdy24lbqdl5g3j456i1tr` (`variant_id` ASC) VISIBLE,
  CONSTRAINT `FK5tuqpdy24lbqdl5g3j456i1tr`
    FOREIGN KEY (`variant_id`)
    REFERENCES `xmate`.`product_variants` (`id`),
  CONSTRAINT `FKkmi4j0c2eed1nlkmo5kmoaxj8`
    FOREIGN KEY (`po_item_id`)
    REFERENCES `xmate`.`purchase_order_items` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `xmate`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xmate`.`cart` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `applied_coupon_code` VARCHAR(255) NULL DEFAULT NULL,
  `user_id` BIGINT NULL DEFAULT NULL,
  `guest_key` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK9emlp6m95v5er2bcqkjsw48he` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `UKbm1bl75m9o3acmxvp452tcvui` (`guest_key` ASC) VISIBLE,
  CONSTRAINT `FK3176mbgur600raom50hqgmsug`
    FOREIGN KEY (`user_id`)
    REFERENCES `xmate`.`customers` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `xmate`.`cart_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xmate`.`cart_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `price_snap` BIGINT NULL DEFAULT NULL,
  `qty` INT NOT NULL,
  `cart_id` BIGINT NULL DEFAULT NULL,
  `variant_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK16wbsp7yd9ei7g8i8pa28ugl3` (`cart_id` ASC, `variant_id` ASC) VISIBLE,
  INDEX `FKpbcx1acwbqj9esdr9hum0o7v7` (`variant_id` ASC) VISIBLE,
  CONSTRAINT `FK1uobyhgl1wvgt1jpccia8xxs3`
    FOREIGN KEY (`cart_id`)
    REFERENCES `xmate`.`cart` (`id`),
  CONSTRAINT `FKpbcx1acwbqj9esdr9hum0o7v7`
    FOREIGN KEY (`variant_id`)
    REFERENCES `xmate`.`product_variants` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `xmate`.`chat_messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xmate`.`chat_messages` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `room` VARCHAR(50) NULL DEFAULT NULL,
  `sender_email` VARCHAR(100) NULL DEFAULT NULL,
  `sender_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `xmate`.`membership_tier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xmate`.`membership_tier` (
  `code` VARCHAR(16) NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `threshold_amount` DECIMAL(12,2) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `xmate`.`customer_membership`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xmate`.`customer_membership` (
  `user_id` BIGINT NOT NULL,
  `period_end` DATE NOT NULL,
  `period_start` DATE NOT NULL,
  `progress_amount` DECIMAL(12,2) NOT NULL,
  `tier_code` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_um_tier` (`tier_code` ASC) VISIBLE,
  CONSTRAINT `fk_um_tier`
    FOREIGN KEY (`tier_code`)
    REFERENCES `xmate`.`membership_tier` (`code`),
  CONSTRAINT `fk_um_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `xmate`.`customers` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `xmate`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xmate`.`orders` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(40) NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `discount_amount` BIGINT NOT NULL,
  `note_internal` VARCHAR(255) NULL DEFAULT NULL,
  `payment_status` ENUM('FAILED', 'PAID', 'REFUNDED', 'UNPAID') NOT NULL,
  `shipping_address` VARCHAR(255) NULL DEFAULT NULL,
  `shipping_fee` BIGINT NOT NULL,
  `shipping_provider` VARCHAR(120) NULL DEFAULT NULL,
  `shipping_status` VARCHAR(50) NULL DEFAULT NULL,
  `status` ENUM('CANCELLED', 'CONFIRMED', 'DELIVERED', 'FAILED', 'PACKED', 'PENDING', 'PENDING_PAYMENT', 'PLACED', 'SHIPPING') NOT NULL,
  `subtotal` BIGINT NOT NULL,
  `total` BIGINT NOT NULL,
  `tracking_code` VARCHAR(120) NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `customer_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UKgt3o4a5bqj59e9y6wakgk926t` (`code` ASC) VISIBLE,
  INDEX `FKpxtb8awmi0dk6smoh2vp1litg` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `FKpxtb8awmi0dk6smoh2vp1litg`
    FOREIGN KEY (`customer_id`)
    REFERENCES `xmate`.`customers` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `xmate`.`discounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xmate`.`discounts` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(60) NULL DEFAULT NULL,
  `conditions_json` JSON NULL DEFAULT NULL,
  `end_at` DATETIME(6) NULL DEFAULT NULL,
  `min_order` DECIMAL(12,2) NULL DEFAULT NULL,
  `start_at` DATETIME(6) NULL DEFAULT NULL,
  `status` VARCHAR(10) NOT NULL,
  `type` ENUM('AUTO', 'CODE') NOT NULL,
  `usage_limit` INT NULL DEFAULT NULL,
  `used_count` INT NOT NULL,
  `value_amount` DECIMAL(12,2) NOT NULL,
  `value_type` ENUM('FIXED', 'PERCENT') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UKbc29q3wh0lqhy0k84bx3afk08` (`code` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `xmate`.`discount_usages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xmate`.`discount_usages` (
  `used_at` DATETIME(6) NOT NULL,
  `customer_id` BIGINT NULL DEFAULT NULL,
  `discount_id` BIGINT NOT NULL,
  `order_id` BIGINT NOT NULL,
  PRIMARY KEY (`discount_id`, `order_id`),
  INDEX `FKhg0vdg50dew3tdbihrs5qja7q` (`customer_id` ASC) VISIBLE,
  INDEX `FK43s7fdx3e2goo1pmsq2lv5slp` (`order_id` ASC) VISIBLE,
  CONSTRAINT `FK43s7fdx3e2goo1pmsq2lv5slp`
    FOREIGN KEY (`order_id`)
    REFERENCES `xmate`.`orders` (`id`),
  CONSTRAINT `FK71pnx68r0ufn6akv7646hiyia`
    FOREIGN KEY (`discount_id`)
    REFERENCES `xmate`.`discounts` (`id`),
  CONSTRAINT `FKhg0vdg50dew3tdbihrs5qja7q`
    FOREIGN KEY (`customer_id`)
    REFERENCES `xmate`.`customers` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `xmate`.`inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xmate`.`inventory` (
  `variant_id` BIGINT NOT NULL,
  `qty_on_hand` INT NOT NULL,
  `qty_reserved` INT NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`variant_id`),
  CONSTRAINT `FK1kv7oe9920t5rlbgvtc1aoojq`
    FOREIGN KEY (`variant_id`)
    REFERENCES `xmate`.`product_variants` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `xmate`.`inventory_movements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xmate`.`inventory_movements` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(6) NOT NULL,
  `note` VARCHAR(255) NULL DEFAULT NULL,
  `qty` INT NOT NULL,
  `ref_id` BIGINT NULL DEFAULT NULL,
  `ref_type` ENUM('MANUAL', 'ORDER', 'PO', 'RETURN') NULL DEFAULT NULL,
  `type` ENUM('ADJUST', 'COMMIT', 'IN', 'OUT', 'RELEASE', 'RESERVE') NOT NULL,
  `created_by` BIGINT NULL DEFAULT NULL,
  `variant_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKo5wo5rt3i3bvxti09ohclqs06` (`created_by` ASC) VISIBLE,
  INDEX `FK52v4o49rlyvhrcxntwrf7k79t` (`variant_id` ASC) VISIBLE,
  CONSTRAINT `FK52v4o49rlyvhrcxntwrf7k79t`
    FOREIGN KEY (`variant_id`)
    REFERENCES `xmate`.`product_variants` (`id`),
  CONSTRAINT `FKo5wo5rt3i3bvxti09ohclqs06`
    FOREIGN KEY (`created_by`)
    REFERENCES `xmate`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `xmate`.`order_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xmate`.`order_items` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `line_total` BIGINT NOT NULL,
  `price` BIGINT NOT NULL,
  `product_name` VARCHAR(255) NULL DEFAULT NULL,
  `qty` INT NOT NULL,
  `order_id` BIGINT NULL DEFAULT NULL,
  `product_id` BIGINT NULL DEFAULT NULL,
  `variant_id` BIGINT NULL DEFAULT NULL,
  `total` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKbioxgbv59vetrxe0ejfubep1w` (`order_id` ASC) VISIBLE,
  INDEX `FKocimc7dtr037rh4ls4l95nlfi` (`product_id` ASC) VISIBLE,
  INDEX `FKemq71edpbn9wsxnxncfn1algp` (`variant_id` ASC) VISIBLE,
  CONSTRAINT `FKbioxgbv59vetrxe0ejfubep1w`
    FOREIGN KEY (`order_id`)
    REFERENCES `xmate`.`orders` (`id`),
  CONSTRAINT `FKemq71edpbn9wsxnxncfn1algp`
    FOREIGN KEY (`variant_id`)
    REFERENCES `xmate`.`product_variants` (`id`),
  CONSTRAINT `FKocimc7dtr037rh4ls4l95nlfi`
    FOREIGN KEY (`product_id`)
    REFERENCES `xmate`.`products` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `xmate`.`otp_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xmate`.`otp_tokens` (
  `id` VARCHAR(255) NOT NULL,
  `attempt_count` INT NOT NULL,
  `channel` VARCHAR(255) NULL DEFAULT NULL,
  `code` VARCHAR(255) NULL DEFAULT NULL,
  `expires_at` DATETIME(6) NULL DEFAULT NULL,
  `purpose` VARCHAR(255) NULL DEFAULT NULL,
  `resend_available_at` DATETIME(6) NULL DEFAULT NULL,
  `used` BIT(1) NOT NULL,
  `user_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `IDX79esliutjxao7masa0pnm3ewh` (`user_id` ASC) VISIBLE,
  INDEX `IDX90rwtrfju5h37e2ylotp3ybn4` (`purpose` ASC) VISIBLE,
  INDEX `IDXcqyai7qdwlr27f81bbglxy8kg` (`expires_at` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `xmate`.`password_reset_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xmate`.`password_reset_tokens` (
  `id` VARCHAR(255) NOT NULL,
  `expires_at` DATETIME(6) NULL DEFAULT NULL,
  `used` BIT(1) NOT NULL,
  `user_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `IDXfy4rmctk9o8ss9m5mr8xpn0dh` (`user_id` ASC) VISIBLE,
  INDEX `IDXsqw3423mry4s2hjp1q9nqbkn8` (`expires_at` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `xmate`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xmate`.`payment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `amount` BIGINT NOT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `method` VARCHAR(255) NULL DEFAULT NULL,
  `raw` LONGTEXT NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  `txn_ref` VARCHAR(255) NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `proof_image` VARCHAR(255) NULL DEFAULT NULL,
  `proof_note` VARCHAR(255) NULL DEFAULT NULL,
  `proof_status` ENUM('APPROVED', 'REJECTED', 'SUBMITTED') NULL DEFAULT NULL,
  `reviewed_at` DATETIME(6) NULL DEFAULT NULL,
  `reviewed_by` VARCHAR(255) NULL DEFAULT NULL,
  `submitted_at` DATETIME(6) NULL DEFAULT NULL,
  `order_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKlouu98csyullos9k25tbpk4va` (`order_id` ASC) VISIBLE,
  CONSTRAINT `FKlouu98csyullos9k25tbpk4va`
    FOREIGN KEY (`order_id`)
    REFERENCES `xmate`.`orders` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `xmate`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xmate`.`permissions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `permission_key` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UKh1ss8mmscopr690vkcj25uj9a` (`permission_key` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 61
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `xmate`.`product_media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xmate`.`product_media` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `media_type` ENUM('IMAGE', 'VIDEO') NOT NULL,
  `is_primary` BIT(1) NOT NULL,
  `sort_order` INT NOT NULL,
  `url` VARCHAR(500) NOT NULL,
  `product_id` BIGINT NOT NULL,
  `variant_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK6d0dleyyjhq9qg62vto0kn01f` (`product_id` ASC) VISIBLE,
  INDEX `FK9etojcf4ulg26bh79uhsr8mio` (`variant_id` ASC) VISIBLE,
  CONSTRAINT `FK6d0dleyyjhq9qg62vto0kn01f`
    FOREIGN KEY (`product_id`)
    REFERENCES `xmate`.`products` (`id`),
  CONSTRAINT `FK9etojcf4ulg26bh79uhsr8mio`
    FOREIGN KEY (`variant_id`)
    REFERENCES `xmate`.`product_variants` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 87
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `xmate`.`product_reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xmate`.`product_reviews` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(1000) NULL DEFAULT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `order_item_id` BIGINT NULL DEFAULT NULL,
  `rating` INT NOT NULL,
  `status` ENUM('APPROVED', 'PENDING', 'REJECTED') NOT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `customer_id` BIGINT NULL DEFAULT NULL,
  `order_id` BIGINT NULL DEFAULT NULL,
  `product_id` BIGINT NULL DEFAULT NULL,
  `variant_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK23003sau3i9tq86acj378o7u9` (`customer_id` ASC) VISIBLE,
  INDEX `FKkpu8o8nqopc4lcqcfnnlpq5vg` (`order_id` ASC) VISIBLE,
  INDEX `FK35kxxqe2g9r4mww80w9e3tnw9` (`product_id` ASC) VISIBLE,
  INDEX `FK2j7dl38e3egi24h4aahrjrpl6` (`variant_id` ASC) VISIBLE,
  CONSTRAINT `FK23003sau3i9tq86acj378o7u9`
    FOREIGN KEY (`customer_id`)
    REFERENCES `xmate`.`customers` (`id`),
  CONSTRAINT `FK2j7dl38e3egi24h4aahrjrpl6`
    FOREIGN KEY (`variant_id`)
    REFERENCES `xmate`.`product_variants` (`id`),
  CONSTRAINT `FK35kxxqe2g9r4mww80w9e3tnw9`
    FOREIGN KEY (`product_id`)
    REFERENCES `xmate`.`products` (`id`),
  CONSTRAINT `FKkpu8o8nqopc4lcqcfnnlpq5vg`
    FOREIGN KEY (`order_id`)
    REFERENCES `xmate`.`orders` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `xmate`.`refresh_token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xmate`.`refresh_token` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `expires_at` DATETIME(6) NULL DEFAULT NULL,
  `revoked` BIT(1) NULL DEFAULT NULL,
  `token` VARCHAR(255) NOT NULL,
  `user_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UKr4k4edos30bx9neoq81mdvwph` (`token` ASC) VISIBLE,
  INDEX `FKmcds309aueean1orth979s5md` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKmcds309aueean1orth979s5md`
    FOREIGN KEY (`user_id`)
    REFERENCES `xmate`.`customers` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `xmate`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xmate`.`roles` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UKofx66keruapi6vyqpv6f2or37` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `xmate`.`role_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xmate`.`role_permissions` (
  `role_id` BIGINT NOT NULL,
  `permission_id` BIGINT NOT NULL,
  PRIMARY KEY (`role_id`, `permission_id`),
  INDEX `FKegdk29eiy7mdtefy5c7eirr6e` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `FKegdk29eiy7mdtefy5c7eirr6e`
    FOREIGN KEY (`permission_id`)
    REFERENCES `xmate`.`permissions` (`id`),
  CONSTRAINT `FKn5fotdgk8d1xvo8nav9uv3muc`
    FOREIGN KEY (`role_id`)
    REFERENCES `xmate`.`roles` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `xmate`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xmate`.`user_roles` (
  `user_id` BIGINT NOT NULL,
  `role_id` BIGINT NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  INDEX `FKh8ciramu9cc9q3qcqiv4ue8a6` (`role_id` ASC) VISIBLE,
  CONSTRAINT `FKh8ciramu9cc9q3qcqiv4ue8a6`
    FOREIGN KEY (`role_id`)
    REFERENCES `xmate`.`roles` (`id`),
  CONSTRAINT `FKhfh9dx7w3ubf1co1vdev94g3f`
    FOREIGN KEY (`user_id`)
    REFERENCES `xmate`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
